version: '3'
services:

  #PHP
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    container_name: app
    restart: always
    ports:
     - "8000:80"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - app-network


  #MySQL
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'doc'
      MYSQL_ROOT_PASSWORD: 'root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
#Redes
networks:
  app-network:
    driver: bridge

#Volumenes
volumes:
  dbdata:
    driver: local
