version: '3'
services:

  #PHP
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    container_name: app2
    restart: always
    ports:
     - "8000:80"
    environment:
      SERVICE_NAME: app2
      SERVICE_TAGS: dev
    networks:
      - app-network


  #MySQL
  db2:
    image: mysql:5.7.22
    container_name: db2
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'doc'
      MYSQL_ROOT_PASSWORD: 'root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    expose:
      - '3306'
    volumes:
      - dbdata2:/var/lib/mysql/
    networks:
      - app-network
#Redes
networks:
  app-network:
    driver: bridge

#Volumenes
volumes:
  dbdata2:
    driver: local
